In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

%matplotlib inline

In [31]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

a.shape


(2, 7)

In [32]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
a[0,1:6:2]

array([2, 4, 6])

In [34]:
c = np.zeros((3,3), dtype = 'int32')
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [35]:
print(np.full_like(c,10))


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [36]:
d = np.full((2,2), 10, dtype = 'int32')
print(d)

[[10 10]
 [10 10]]


In [37]:
e = np.full_like(d,99)
print(e)

[[99 99]
 [99 99]]


In [38]:
f = np.random.randint(2,5, size = (2,2))
print(f)

[[2 4]
 [2 3]]


In [39]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
arr1 = np.array([[1,2,3]])
arr2 = np.repeat(arr1, 3, axis = 0)
print(arr2)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [41]:
output = np.zeros((7,7))
print(output)

z = np.ones(((5,5)))
print(z)



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
z[2,2] = 5
output[1:-1,1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [43]:
a = np.array([1,2,3,4,5])
b = a.copy()
b[2] = 20
print(a)
print(b)

[1 2 3 4 5]
[ 1  2 20  4  5]


In [44]:
a = np.array([1,2,3,4,5])
b = np.ones(5)
print(a,b)

[1 2 3 4 5] [1. 1. 1. 1. 1.]


In [45]:
c = a/3
print(c)
print(a)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[1 2 3 4 5]


In [46]:
print(a)
print(a**2)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [47]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print(b)

c = np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [48]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [49]:
a = np.random.randint(0,11, size = (3,3))
print(a)

[[ 0  2  8]
 [10  4  4]
 [10 10  7]]


In [50]:
b = np.max(a, axis = 0)
print(b)
np.median(b)


[10 10  8]


10.0

In [51]:
a = np.random.randint(0,11, size = (2,3))
print(a)

[[0 8 7]
 [4 6 0]]


In [52]:
b = np.reshape(a, (3,2))
print(b)

[[0 8]
 [7 4]
 [6 0]]


In [53]:
a = np.random.randint(0,11, size = (1,4))
b = np.random.randint(0,11, size = (1,4))
print(a,b)

[[10  5  0  4]] [[0 3 7 2]]


In [54]:
np.hstack([a,b])

array([[10,  5,  0,  4,  0,  3,  7,  2]])

In [55]:
a = np.zeros(4)
b = np.ones(4)
print(a,b)

[0. 0. 0. 0.] [1. 1. 1. 1.]


In [56]:
np.hstack([a,b])

array([0., 0., 0., 0., 1., 1., 1., 1.])

In [57]:
a = np.random.randint(0,11, size = (6,5))
print(a)

[[ 1  2  1  0  1]
 [ 6  4 10  6  6]
 [ 7  6  3  6  6]
 [ 7  1  7  4  4]
 [ 6  6  6  0  7]
 [10  2 10  5  8]]


In [58]:
a[0:4, 1:5]

array([[ 2,  1,  0,  1],
       [ 4, 10,  6,  6],
       [ 6,  3,  6,  6],
       [ 1,  7,  4,  4]])